//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCalProj.EasyCalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int SerialNumber { get; set; }
        public string ActivityName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StartTime { get; set; }
        public string Endtime { get; set; }
        public string Location { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
    }
}
