//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCalProj.EasyCalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        public string LecturerName { get; set; }
        public string Department { get; set; }
        public string Course { get; set; }
        public string RecpHours { get; set; }
        public string PhoneNumber { get; set; }
    }
}
