//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCalProj.EasyCalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks1
    {
        public int SerialNum { get; set; }
        public string Course { get; set; }
        public string TaskName { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan SubmitTime { get; set; }
    }
}
