//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCalProj.EasyCalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public string CourseName { get; set; }
        public Nullable<int> AcademicYear { get; set; }
        public string LecturerName { get; set; }
        public string Day { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}
